log:
  level: error
  file: ./mosdns.log

plugins:
  - tag: hosts
    type: hosts
    args:
      files: ./rule/hosts.txt

  - tag: lazy_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400

  - tag: geoip_cn
    type: ip_set
    args:
      files: ./rule/geoip_cn.txt

  - tag: gfw_ip
    type: ip_set
    args:
      files: ./rule/gfw_ip.txt

  - tag: geosite_cn
    type: domain_set
    args:
      files: ./rule/geosite_cn.txt

  - tag: geosite_no_cn
    type: domain_set
    args:
      files: ./rule/geosite_geolocation-!cn.txt

  - tag: category_ads_all
    type: domain_set
    args:
      files: ./rule/geosite_category-ads-all.txt

  - tag: win_spy
    type: domain_set
    args:
      files: ./rule/geosite_win-spy.txt

  - tag: win_update
    type: domain_set
    args:
      files: ./rule/geosite_win-update.txt

  - tag: win_extra
    type: domain_set
    args:
      files: ./rule/geosite_win-extra.txt

  - tag: local_ptr
    type: domain_set
    args:
      files: ./rule/local-ptr.txt

  - tag: ecs_hk
    type: ecs_handler
    args:
      forward: false
      preset: 203.142.100.0
      send: false
      mask4: 24
      mask6: 48

  - tag: type_sequence
    type: sequence
    args:
      - matches: qtype 12
        exec: mark 1
      - matches: qtype 65
        exec: mark 1
      - matches: qtype 255
        exec: mark 1
      - matches: mark 1
        exec: reject 0

  - tag: win_sequence
    type: sequence
    args:
      - matches: qname $win_spy
        exec: mark 2
      - matches: qname $win_update
        exec: mark 2
      - matches: qname $win_extra
        exec: mark 2
      - matches: mark 2
        exec: reject 3
        
  - tag: ads_sequence
    type: sequence
    args:
      - matches: qname $category_ads_all
        exec: mark 3
      - matches: qname $local_ptr
        exec: mark 3
      - matches: mark 3
        exec: reject 3

  - tag: rate_limit
    type: rate_limiter
    args:
      qps: 20
      burst: 40
      mask4: 32
      mask6: 48

  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
          - addr: https://sm2.doh.pub/dns-query
            dial_addr: 106.55.91.174
          - addr: https://223.5.5.5/dns-query
          - addr: tcp://180.184.1.1
            enable_pipeline: true

  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
          - addr: https://146.112.41.2/dns-query
          - addr: tls://76.76.2.11
            enable_pipeline: true
            
  - tag: forward_easymosdns
    type: forward
    args:
      upstreams:
          - addr: https://mosdns.apad.pro/api-query
            bootstrap: 119.29.29.29

  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: "resp_ip $geoip_cn"
        exec: accept
        
  - tag: remote_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $ecs_hk
      - exec: $forward_remote
      - matches: "!resp_ip $gfw_ip"
        exec: accept
        
  - tag: easymosdns_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $ecs_hk
      - exec: $forward_easymosdns
      - matches: "!resp_ip $gfw_ip"
        exec: accept

  - tag: has_wanted_ans_sequence
    type: sequence
    args:
      - matches: has_wanted_ans
        exec: accept

  - tag: fallback
    type: fallback
    args:
      primary: easymosdns_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: false

  - tag: main_sequence
    type: sequence
    args:
      - matches: "!$rate_limit"
        exec: reject 3
      - exec: $hosts
      - exec: jump has_wanted_ans_sequence
      - exec: $lazy_cache
      - exec: jump type_sequence
      - exec: jump win_sequence
      - exec: jump ads_sequence
      - matches: qname $geosite_cn
        exec: jump local_sequence
      - matches: qname $geosite_no_cn
        exec: goto remote_sequence
      - exec: $fallback

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":53"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":53"
